"""
packflow roll-in splash animation.

Runtime deps: stdlib only.
Frame data is in _frames.py — a plain Python file generated by
tools/bake_frames.py.
"""

from __future__ import annotations

import os
import sys
import time


def _can_animate() -> bool:
    if not sys.stdout.isatty():
        return False
    if os.environ.get("CI") or os.environ.get("NO_COLOR"):
        return False
    if os.environ.get("TERM") in ("dumb", ""):
        return False
    if "ipykernel" in sys.modules or "IPython" in sys.modules:
        return False
    return True


def roll_in(force: bool = False) -> None:
    """Play the packflow roll-in animation.

    Args:
        force: Skip environment guards. Used by ``packflow roll``.
    """
    if not force and not _can_animate():
        return

    try:
        from packflow._frames import ANIM_HEIGHT, FRAMES, ROWS
    except ImportError:
        return

    sys.stdout.write("\n" * ANIM_HEIGHT + "\033[?25l")
    sys.stdout.flush()
    try:
        for delay, row_indices in FRAMES:
            sys.stdout.write(f"\033[{ANIM_HEIGHT}A")
            for idx in row_indices:
                sys.stdout.write(ROWS[idx] + "\n")
            sys.stdout.flush()
            if delay > 0:
                time.sleep(delay)
    except KeyboardInterrupt:
        pass
    finally:
        sys.stdout.write("\033[?25h")
        sys.stdout.flush()
