#!/usr/bin/env python3
"""
Capture the splash_render animation and write a pure-Python frame table.

Patches show() and time.sleep in splash_render, captures every rendered frame
as a list of row strings, deduplicates into a row pool, and writes _frames.py.

Run from the packflow/ directory:
    python tools/bake_frames.py <logo.png> <font.ttf> [--width <width>]

Output: src/packflow/_frames.py   (plain Python)
Requires: pillow, numpy, and the font — only at bake time.
"""

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import splash_render


def render_row(buf_row: list, col_row: list) -> str:
    """Render one row of (char, color) cells to an ANSI string."""
    line = ""
    cur = None
    for ch, c in zip(buf_row, col_row):
        if c != cur:
            line += "\033[0m" if c is None else c
            cur = c
        line += ch
    if cur is not None:
        line += "\033[0m"
    return line


def capture(logo: str, font: str, term_width: int) -> tuple[int, list]:
    """Return (anim_h, [(delay, [row_str, ...]), ...])."""
    frames: list[list] = []

    def patched_show(buf, col=None):
        rows = [
            render_row(buf[y], col[y] if col else [None] * len(buf[y]))
            for y in range(len(buf))
        ]
        frames.append([rows, 0.0])

    def fake_sleep(t: float) -> None:
        if frames:
            frames[-1][1] = t

    orig_show = splash_render.show
    orig_sleep = splash_render.time.sleep
    orig_stdout = sys.stdout
    sys.stdout = open(sys.__stdout__.fileno(), "w", closefd=False)

    splash_render.show = patched_show
    splash_render.time.sleep = fake_sleep
    try:
        splash_render.roll_in(logo, font, term_width)
    finally:
        splash_render.show = orig_show
        splash_render.time.sleep = orig_sleep
        sys.stdout = orig_stdout

    return splash_render.ANIM_HEIGHT, frames


def write_frames_py(out_path: Path, anim_h: int, frames: list) -> None:
    # Build deduplicated row pool (insertion order preserved via dict)
    row_pool: dict[str, int] = {}
    frame_indices: list[tuple] = []

    for rows, delay in frames:
        indices = []
        for row in rows:
            if row not in row_pool:
                row_pool[row] = len(row_pool)
            indices.append(row_pool[row])
        frame_indices.append((delay, tuple(indices)))

    rows_list = list(row_pool.keys())

    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", encoding="utf-8") as f:
        f.write("# Auto-generated by tools/bake_frames.py — do not edit.\n")
        f.write(f"ANIM_HEIGHT = {anim_h}\n\n")

        f.write("ROWS = [\n")
        for row in rows_list:
            f.write(f"    {repr(row)},\n")
        f.write("]\n\n")

        f.write("FRAMES = [\n")
        for delay, indices in frame_indices:
            f.write(f"    ({delay!r}, {indices!r}),\n")
        f.write("]\n")

    size = out_path.stat().st_size
    print(
        f"Saved {out_path}\n"
        f"  {len(frames)} frames  {len(rows_list)} unique rows  {size:,} bytes"
    )


def main(args: argparse.Namespace) -> None:
    anim_h, frames = capture(args.logo, args.font, args.width)
    print(f"Captured {len(frames)} frames  anim_h={anim_h}")
    write_frames_py(Path(args.output), anim_h, frames)


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("logo", help="path to packflow-logo-32px.png")
    ap.add_argument("font", help="path to JosefinSans-VariableFont_wght.ttf")
    ap.add_argument("-W", "--width", type=int, default=80)
    ap.add_argument("-o", "--output", default="src/packflow/_frames.py")
    main(ap.parse_args())
